name: Automatic Semantic Versioning

# Restrict the workflow to the main branch and ignore tags
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Initialize NPM
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Create a release
        uses: gevorg-martir/version-me@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "[DEBUG] Show outputs"
        run: |
          echo version-changed = '${{ steps.release.outputs.version-changed }}'
          echo new-version = '${{ steps.release.outputs.new-version }}'

      - name: Create a new tag
        if: steps.release.outputs.version-changed == 'true'
        run: |
          # git config --global user.name "github-actions[bot]"
          # git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ steps.release.outputs.new-version }} -m "Release version ${{ steps.release.outputs.new-version }}"
          git push origin v${{ steps.release.outputs.new-version }}