name: Automatic Semantic Versioning

# Restrict the workflow to the main branch and ignore tags
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Initialize NPM
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -am "chore(release): ${nextRelease.version}"
          npx semantic-release